server:
  port: 80

spring:
  #  application:
  #    name: zookeeper-order-payment
  #  cloud:
  #    zookeeper:
  #      connect-string: 172.27.98.87:2181
  application:
    name: consul-order-payment
  cloud:
    consul:
      host: 172.27.98.87
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true    #设置host为首选地址
        heartbeat:
          enabled: true #发送心跳包