server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service
  #    zipkin:
  #      base-url: http://localhost:9411
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.27.98.87:3307/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 666666
  sleuth:
    sampler:
      probability: 1 #采样率 1为全部采集
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true  #访问路径可以显示IP地址
#    lease-renewal-interval-in-seconds: 1  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-expiration-duration-in-seconds: 2 #收到最后一次心跳

